services:
  db:
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=later_test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10