CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email VARCHAR(256) NOT NULL UNIQUE,
    name VARCHAR(256),
    state VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id),
    url VARCHAR,
    resolved_url VARCHAR,
    title VARCHAR(256),
    mimeType VARCHAR(64),
    has_image BOOLEAN,
    has_video BOOLEAN,
    date_resolved TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tags (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    item_id BIGINT REFERENCES items(id),
    name VARCHAR(256)
);

CREATE TABLE IF NOT EXISTS item_notes (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    item_id BIGINT REFERENCES items(id),
    text VARCHAR(256),
    created TIMESTAMP
);